CREATE OR REPLACE FUNCTION DATEDIFF(DATE_FROM IN DATE, DATE_UNTIL IN DATE)
    RETURN NUMBER AS DIFF NUMBER
    BEGIN
    DIFF := EXTRACT(YEAR FROM DATE_UNTIL) - EXTRACT(YEAR FROM DATE_TO);
RETURN DIFF
END; 

--1--
SELECT WIN.WINNER_NAME, DATEDIFF(WIN.BIRTH_DATE, PZ.PRIZE_YEAR) 
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.PRIZE_WINNERS PW ON PZ.PRIZE_ID = PW.PRIZE_ID
    INNER JOIN EJERCICIOU2.WINNERS WIN ON PW.WINNER_ID = WIN.WINNER_ID;
GROUP BY WIN.WINNER_NAME;

--2--

variable my_date varchar2(30)

exec :my_date := '02-apr-2018';

SELECT WIN.WINNER_NAME, DATEDIFF(WIN.BIRTH_DATE, MY_DATE) 
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.PRIZE_WINNERS PW ON PZ.PRIZE_ID = PW.PRIZE_ID
    INNER JOIN EJERCICIOU2.WINNERS WIN ON PW.WINNER_ID = WIN.WINNER_ID;
GROUP BY WIN.WINNER_NAME;

--3--