--Obtener los 5 premios nobel mas recientes
SELECT PZ.PRIZE_YEAR, PZ.PRIZE_NAME FROM EJERCICIOU2.PRIZES PZ
    WHERE ROWNUM <= 5
    ORDER BY PZ.PRIZE_YEAR DESC;

--Obtener los ultimos 10 premios nobel de fisica
SELECT PZ.PRIZE_YEAR, PZ.PRIZE_NAME, CAT.CATEGORY 
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.CATEGORIES CAT ON PZ.CATEGORY_ID = CAT.CAATEGORY_ID
        WHERE ROWNUM <= 10 
        ORDER BY PZ.PRIZE_YEAR DESC;

--obtener las ultimas personas que han ganado mas de un premio
/*
SELECT PZ.PRIZE_ID, PZ.PRIZE_NAME, WIN.WINNER_NAME, SUM() PRIZES_WON
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.PRIZE_WINNERS PW ON PZ.PRIZE_ID = PW.PRIZE_ID
    INNER JOIN EJERCICIOU2.WINNERS WIN ON PW.WINNER_ID = WIN.WINNER_ID*/

--obtener el campo/lenguaje con mas premios nobel
SELECT FIL.FIELD, COUNT(PZ.FIELD_ID) NUM_OF_TIMES_GIVEN
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.FIELDS FIL ON PZ.FIELD_ID = FIL.FIELD_ID
GROUP BY FIL.FIELD
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EJERCICIOU2.PRIZES GROUP BY FIELD_ID);

--obtener los premios ganados desde 1980 al 1998 en quimica
SELECT PZ.PRIZE_ID, PZ.PRIZE_NAME
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.CATEGORIES CAT ON PZ.CATEGORY_ID = CAT.CAATEGORY_ID
    WHERE CAT.CATEGORY='QUIMICA' AND EXTRACT(YEAR FROM PZ.PRIZE_YEAR)>=1980 AND EXTRACT(YEAR FROM PZ.PRIZE_YEAR)<=1998
    ORDER BY PZ.PRIZE_ID; 

SELECT PROD.PRODUCT_ID , OP.QUANTITY, ORD.ORDER_DATE
    FROM BRIANNA.ORDERS_PRODUCTS OP
    INNER JOIN BRIANNA.ORDERS ORD ON OP.ORDER_ID = ORD.ORDER_ID
    INNER JOIN BRIANNA.PRODUCTS PROD ON OP.PRODUCT_ID = PROD.PRODUCT_ID
WHERE ROWNUM <= 10 AND EXTRACT(YEAR FROM ORD.ORDER_DATE)=2015 ORDER BY OP.QUANTITY ASC;


--obtener el premio nobel ganado en menos ocaciones
SELECT CAT.CATEGORY, COUNT(PZ.CATEGORY_ID) NUM_OF_TIMES_WON
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.CATEGORIES CAT ON PZ.CATEGORY_ID = CAT.CAATEGORY_ID
GROUP BY CAT.CATEGORY
HAVING COUNT(*) = (SELECT MIN(COUNT(*)) FROM EJERCICIOU2.PRIZES GROUP BY CATEGORY_ID);


--obtener e pais con mas premios nobel
SELECT CNT.COUNTRY, COUNT(PW.COUNTRY_ID) NUM_OF_NOBEL_PRIZES
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.PRIZE_WINNERS PW ON PZ.PRIZE_ID = PW.PRIZE_ID
    INNER JOIN EJERCICIOU2.COUNTRIES CNT ON PW.COUNTRY_ID = CNT.COUNTRY_ID
GROUP BY CNT.COUNTRY
HAVING COUNT(*) = (SELECT MAX(COUNT(*)) FROM EJERCICIOU2.PRIZE_WINNERS GROUP BY COUNTRY_ID);


--obtener los premios nobel compartidos (mas de 1 ganador en la misma categoria y ano)
SELECT PZ.PRIZE_ID, COUNT(PZ.PRIZE_ID) AS NUM 
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.PRIZE_WINNERS PW ON PZ.PRIZE_ID = PW.PRIZE_ID
    INNER JOIN EJERCICIOU2.WINNERS WIN ON PW.WINNER_ID = WIN.WINNER_ID
    GROUP BY PZ.PRIZE_ID; 

--obtener el promedio de edad de todos los ganadores al momento en que ganan su premio
SELECT WIN.WINNER_NAME, AVG(PZ.PRIZE_YEAR - EXTRACT(YEAR FROM WIN.BIRTH_DATE)) AS PROMEDIO_EDAD
    FROM EJERCICIOU2.PRIZES PZ
    INNER JOIN EJERCICIOU2.PRIZE_WINNERS PW ON PZ.PRIZE_ID = PW.PRIZE_ID
    INNER JOIN EJERCICIOU2.WINNERS WIN ON PW.WINNER_ID = WIN.WINNER_ID;

